### ISSUE TITLE
reduce crafting time, add setting to get blank concrete back on mining

### ISSUE THREAD

**Issue by dtrauma** [Larandar/Concrete-Tints#3]
Hi, I added two things to the code:

 - I used hazard concrete's recipe as a template (so you get fast crafting, also simplifies the code)
 - I added a setting to get back untinted concrete when you pick it back up from the floor.

Here's a filebin with a git bundle, a patch series and a simple diff:

https://filebin.net/gq5gupno6y669v16

**Comment by Larandar** [comment]
Hi,

Thanks for the suggestions, unfortunately, you used 1.0 code for the diff so I was not able to just patch it. So I recreated your modification with some small tweaking.
